# Generated by Django 5.0.6 on 2024-05-19 06:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('author', models.CharField(max_length=30)),
                ('genre', models.CharField(max_length=30)),
                ('published_year', models.IntegerField()),
                ('isbn', models.IntegerField()),
                ('publisher', models.CharField(max_length=30)),
                ('pages', models.IntegerField()),
                ('lenguage', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('over_image_url', models.ImageField(upload_to='')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2024, 5, 19, 1, 14, 46, 537716))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2024, 5, 19, 1, 14, 46, 537716))),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
