# Generated by Django 5.0.6 on 2024-05-19 06:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 19, 1, 15, 26, 527914)),
        ),
        migrations.AlterField(
            model_name='books',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 19, 1, 15, 26, 527914)),
        ),
    ]
